### **Assignment: Introduction to Linear Algebra and NumPy**

#### **Objective:**
This assignment will help you build a solid understanding of basic Linear Algebra concepts using Python and the NumPy library. You'll learn to create and manipulate arrays, perform mathematical operations, and explore properties and methods of arrays.


### **Working with NumPy**

NumPy is a powerful Python library for numerical computations, which allows easy manipulation of arrays and matrices.

**Task 1:** 
- Import the `numpy` library and check its version.


In [1]:
import numpy as np

# Check the version of numpy
print("NumPy Version:", np.__version__)

NumPy Version: 2.4.4



### **Creating a NumPy Array:**

NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

**Task 2:**
- Create a 1D NumPy array from a Python list of numbers: `[1, 2, 3, 4, 5]`.
- Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
- Generate an array of 10 evenly spaced values between 0 and 5.

In [2]:
# Create a 1D NumPy array from a Python list
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", array_1d)

# Create a 2D NumPy array of shape (3x3) using numbers 1 to 9
array_2d = np.arange(1, 10).reshape(3, 3)
print("\n2D Array (3x3):\n", array_2d)

# Generate an array of 10 evenly spaced values between 0 and 5
evenly_spaced_array = np.linspace(0, 5, 10)
print("\nEvenly Spaced Array:\n", evenly_spaced_array)

1D Array:
 [1 2 3 4 5]

2D Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Evenly Spaced Array:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### **Indexing and Slicing Arrays:**

Indexing and slicing allow you to access and modify specific elements of an array.

**Task 3:**
- Access the element in the second row, third column of the 2D array you created above.
- Slice the first two rows and the first two columns from the same array.
- Modify the value in the last row and first column to 100.


In [3]:
# Access the element in the second row, third column (index 1, index 2)
element = array_2d[1, 2]
print("Element at 2nd row, 3rd column:", element)

# Slice the first two rows and the first two columns
sliced_array = array_2d[:2, :2]
print("\nSliced Array (first 2 rows & cols):\n", sliced_array)

# Modify the value in the last row and first column to 100 (index 2, index 0)
array_2d[2, 0] = 100
print("\nModified 2D Array:\n", array_2d)

Element at 2nd row, 3rd column: 6

Sliced Array (first 2 rows & cols):
 [[1 2]
 [4 5]]

Modified 2D Array:
 [[  1   2   3]
 [  4   5   6]
 [100   8   9]]


### **Properties and Methods of NumPy Arrays**

NumPy arrays have several useful properties and methods.

**Task 4:**
- Find the shape, size, and data type of the 2D array.
- Change the 1D array into a 2D array of shape (5,1).
- Flatten a multi-dimensional array back into a 1D array.

In [4]:
# Find the shape, size, and data type of the 2D array
print("Shape of 2D array:", array_2d.shape)
print("Size of 2D array (total elements):", array_2d.size)
print("Data type of 2D array:", array_2d.dtype)

# Change the 1D array into a 2D array of shape (5,1)
reshaped_1d = array_1d.reshape((5, 1))
print("\nReshaped 1D Array to (5,1):\n", reshaped_1d)

# Flatten a multi-dimensional array back into a 1D array
flattened_array = array_2d.flatten()
print("\nFlattened 2D Array:\n", flattened_array)

Shape of 2D array: (3, 3)
Size of 2D array (total elements): 9
Data type of 2D array: int64

Reshaped 1D Array to (5,1):
 [[1]
 [2]
 [3]
 [4]
 [5]]

Flattened 2D Array:
 [  1   2   3   4   5   6 100   8   9]


### **Operations on NumPy Arrays**

Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

**Task 5:**
- Add 5 to every element in the 1D array.
- Multiply the 2D array by 3.
- Perform matrix multiplication between the following two arrays:  
    ```python
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

In [5]:
.# Add 5 to every element in the 1D array
added_1d = array_1d + 5
print("1D Array + 5:\n", added_1d)

# Multiply the 2D array by 3
multiplied_2d = array_2d * 3
print("\n2D Array multiplied by 3:\n", multiplied_2d)

# Perform matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# You can use np.dot(A, B) or the @ operator for matrix multiplication
matrix_product = A @ B
print("\nMatrix Multiplication of A and B:\n", matrix_product)

1D Array + 5:
 [ 6  7  8  9 10]

2D Array multiplied by 3:
 [[  3   6   9]
 [ 12  15  18]
 [300  24  27]]

Matrix Multiplication of A and B:
 [[19 22]
 [43 50]]


### **Understanding Broadcasting**

Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

**Task 6:**
- Create a 3x3 matrix of ones and a 1D array of length 3.
- Add the 1D array to each row of the matrix using broadcasting.

In [6]:
# Create a 3x3 matrix of ones and a 1D array of length 3
matrix_ones = np.ones((3, 3))
array_1d_len3 = np.array([10, 20, 30])

print("3x3 Matrix of Ones:\n", matrix_ones)
print("\n1D Array of length 3:\n", array_1d_len3)

# Add the 1D array to each row of the matrix using broadcasting
broadcast_result = matrix_ones + array_1d_len3
print("\nResult of Broadcasting (Matrix + 1D Array):\n", broadcast_result)

3x3 Matrix of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

1D Array of length 3:
 [10 20 30]

Result of Broadcasting (Matrix + 1D Array):
 [[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]
